# In .github/workflows/deploy.yml

name: Deploy Backend to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    name: Deploy Backend to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install
        working-directory: ./functions

      # --- DE GECORRIGEERDE STAP ---
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          # We combineren alle argumenten in de 'args' parameter
          args: deploy --only functions --project richting-sales-d764a
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
